//! Tauri commands for frontend-backend communication.

// The `#[tauri::command]` attribute macro expands to argument-extraction glue
// that trips these lints on the generated code rather than on anything we wrote.
#![expect(
    clippy::unreachable,
    clippy::let_underscore_must_use,
    reason = "generated by the #[tauri::command] attribute macro"
)]

use crate::error::CommandError;
use crate::error::ErrorCode;
use crate::events::AppEvent;
use crate::i18n;
use crate::logging;
use crate::notification;
use crate::polling;
use crate::state::AllDailyRewardStatus;
use crate::state::AllResources;
use crate::state::AppState;
use crate::window;
use camino::Utf8Path;
use jiff::Timestamp;
use serde::Serialize;
use storekeeper_core::AppConfig;
use storekeeper_core::GameId;
use storekeeper_core::Region;
use storekeeper_core::SecretsConfig;
use tauri::AppHandle;
use tauri::Emitter;
use tauri::Manager;
use tauri::State;
use tauri_plugin_autostart::ManagerExt;
use tauri_plugin_notification::NotificationExt;

/// Gets all cached resources.
#[tauri::command]
pub async fn get_all_resources(state: State<'_, AppState>) -> Result<AllResources, CommandError> {
    Ok(state.get_resources().await)
}

/// Refreshes resources from all configured games.
#[tauri::command]
pub async fn refresh_resources(app_handle: AppHandle) -> Result<AllResources, CommandError> {
    Ok(polling::refresh_now(&app_handle).await?)
}

/// Gets the current application configuration.
#[tauri::command]
pub async fn get_config() -> Result<AppConfig, CommandError> {
    Ok(AppConfig::load()?)
}

/// Gets the current secrets configuration.
#[tauri::command]
pub async fn get_secrets() -> Result<SecretsConfig, CommandError> {
    Ok(SecretsConfig::load()?)
}

/// Result returned by `save_and_apply`.
#[derive(Serialize)]
pub struct SaveResult {
    /// The effective locale after applying changes.
    effective_locale: String,
}

/// Saves config + secrets and applies only the changes that are needed.
///
/// Combines write + diff + selective apply into a single IPC call:
/// 1. Writes config.toml and secrets.toml to disk
/// 2. Diffs old (from state) vs new (from params) in-memory - no re-read
/// 3. Selectively applies changes based on the diff
/// 4. Returns the effective locale for frontend sync
#[tauri::command]
pub async fn save_and_apply(
    config: AppConfig,
    secrets: SecretsConfig,
    app_handle: AppHandle,
) -> Result<SaveResult, CommandError> {
    let state = app_handle.state::<AppState>();

    let (old_config, old_secrets) = {
        let inner = state.inner.read().await;
        (inner.config.clone(), inner.secrets.clone())
    };

    config.save()?;
    secrets.save()?;
    tracing::info!("Configuration and secrets saved to disk");

    // Diff against the in-memory snapshot rather than re-reading from disk.
    let diff = crate::config_diff::compute(&old_config, &config, &old_secrets, &secrets);

    if diff.is_empty() {
        tracing::info!("Config unchanged, nothing to apply");
        return Ok(SaveResult {
            effective_locale: i18n::get_current_locale(),
        });
    }

    tracing::info!(
        locale_changed = diff.general.locale_changed,
        autostart_changed = diff.general.autostart_changed,
        log_level_changed = diff.general.log_level_changed,
        needs_registry_rebuild = diff.needs_registry_rebuild,
        games_to_refresh = ?diff.games_to_refresh,
        games_to_reset_notifications = ?diff.games_to_reset_notifications,
        "Config diff computed"
    );

    state
        .apply_config(config, secrets, diff.needs_registry_rebuild)
        .await;

    // Wake the scheduler so it re-evaluates auto-claim config immediately
    state.wake_scheduler();

    if diff.general.locale_changed {
        let language = {
            let inner = state.inner.read().await;
            inner.config.general.language.clone()
        };
        let effective_locale = i18n::resolve_locale(language.as_deref());
        if let Err(e) = i18n::set_locale(effective_locale) {
            tracing::warn!(error = %e, "Failed to update i18n locale");
        }
        if let Err(e) = crate::tray::build_tray_menu(&app_handle) {
            tracing::warn!(error = %e, "Failed to rebuild tray menu");
        }
    }

    if diff.general.log_level_changed {
        let level = {
            let inner = state.inner.read().await;
            inner.config.general.log_level.clone()
        };
        app_handle.state::<logging::LogFilter>().set_level(&level);
    }

    if diff.general.autostart_changed {
        let autostart_enabled = {
            let inner = state.inner.read().await;
            inner.config.general.autostart
        };
        let autolaunch = app_handle.autolaunch();
        let autostart_result = if autostart_enabled {
            autolaunch.enable()
        } else {
            autolaunch.disable()
        };
        if let Err(e) = autostart_result {
            tracing::warn!(error = %e, "Failed to sync autostart state");
        }
    }

    if !diff.games_to_reset_notifications.is_empty() {
        let mut inner = state.inner.write().await;
        for game_id in &diff.games_to_reset_notifications {
            inner.notification_tracker.clear_for_game(*game_id);
        }
    }

    if !diff.games_to_refresh.is_empty()
        && let Err(e) = polling::refresh_games(&app_handle, &diff.games_to_refresh).await
    {
        tracing::warn!(error = %e, "Failed to refresh games after config change");
    }

    tracing::info!("Configuration applied successfully");
    Ok(SaveResult {
        effective_locale: i18n::get_current_locale(),
    })
}

/// Create `dir` when absent, then reveal it in the OS file manager.
fn reveal_directory(dir: &Utf8Path) -> Result<(), CommandError> {
    if !dir.exists() {
        fs_err::create_dir_all(dir)?;
    }

    #[cfg(target_os = "windows")]
    {
        std::process::Command::new("explorer").arg(dir).spawn()?;
    }

    #[cfg(target_os = "macos")]
    {
        std::process::Command::new("open").arg(dir).spawn()?;
    }

    #[cfg(target_os = "linux")]
    {
        std::process::Command::new("xdg-open").arg(dir).spawn()?;
    }

    Ok(())
}

/// Open the configuration folder in the system file manager.
#[tauri::command]
pub fn open_config_folder() -> Result<(), CommandError> {
    reveal_directory(&storekeeper_core::AppConfig::config_dir()?)
}

/// Open the log folder in the system file manager.
#[tauri::command]
pub fn open_log_folder() -> Result<(), CommandError> {
    reveal_directory(&logging::log_dir()?)
}

/// Open the log viewer window, or focus it when it is already open.
///
/// Build the window asynchronously because `WebviewWindowBuilder::build` can
/// deadlock on Windows when a synchronous command calls it.
#[tauri::command]
pub async fn open_logs_window(app_handle: AppHandle) -> Result<(), CommandError> {
    window::open_logs_window(&app_handle)?;
    Ok(())
}

/// Return the last `lines` entries of the current day's log file as raw JSON.
///
/// The viewer polls every couple of seconds and each read covers up to one
/// megabyte, so file I/O runs on the blocking pool.
#[tauri::command]
pub async fn read_log_tail(lines: usize) -> Result<Vec<String>, CommandError> {
    tauri::async_runtime::spawn_blocking(move || logging::read_tail(lines))
        .await
        .map_err(|e| CommandError::internal(format!("log read task failed: {e}")))?
        .map_err(CommandError::from)
}

/// Gets the cached daily reward status for all games.
#[tauri::command]
pub async fn get_daily_reward_status(
    state: State<'_, AppState>,
) -> Result<AllDailyRewardStatus, CommandError> {
    Ok(state.get_daily_reward_status().await)
}

/// Refreshes the daily reward status from all configured games.
#[tauri::command]
pub async fn refresh_daily_reward_status(
    state: State<'_, AppState>,
) -> Result<AllDailyRewardStatus, CommandError> {
    let status = state.fetch_all_daily_reward_status().await;
    state.set_daily_reward_status(status.clone()).await;
    Ok(status)
}

/// Claims daily reward for a specific game.
#[tauri::command]
pub async fn claim_daily_reward_for_game(
    game_id: GameId,
    app_handle: AppHandle,
    state: State<'_, AppState>,
) -> Result<serde_json::Value, CommandError> {
    tracing::info!(game_id = ?game_id, "Manual daily reward claim requested for specific game");
    let result = state.claim_daily_reward_for_game(game_id).await?;

    if let Ok(game_status) = state.get_daily_reward_status_for_game(game_id).await {
        let mut current_status = state.get_daily_reward_status().await;
        current_status.games.insert(game_id, game_status);
        current_status.last_checked = Some(Timestamp::now());
        state.set_daily_reward_status(current_status).await;
    }

    // Notify frontend so atoms re-fetch claim status
    if let Err(e) = app_handle.emit(AppEvent::DailyRewardClaimed.as_str(), &result) {
        tracing::warn!(error = %e, "Failed to emit DailyRewardClaimed event");
    }

    Ok(result)
}

/// Gets the daily reward status for a specific game.
#[tauri::command]
pub async fn get_daily_reward_status_for_game(
    game_id: GameId,
    state: State<'_, AppState>,
) -> Result<serde_json::Value, CommandError> {
    Ok(state.get_daily_reward_status_for_game(game_id).await?)
}

/// Sends a preview notification for a specific game resource using cached data.
#[tauri::command]
pub async fn send_preview_notification(
    game_id: GameId,
    resource_type: String,
    app_handle: AppHandle,
    state: State<'_, AppState>,
) -> Result<(), CommandError> {
    let resources = state.get_resources().await;
    let game_name = notification::game_display_name(game_id);
    let resource_name = notification::resource_display_name(&resource_type);

    let body = resources
        .games
        .get(&game_id)
        .and_then(|v| v.as_array())
        .and_then(|arr| {
            arr.iter().find(|obj| {
                obj.get("type")
                    .and_then(serde_json::Value::as_str)
                    .is_some_and(|t| t == resource_type)
            })
        })
        .and_then(|obj| obj.get("data"))
        .and_then(|data| {
            let info = notification::extract_resource_info(&resource_type, data)?;
            let now = Timestamp::now();
            Some(notification::build_notification_body(&info, now))
        })
        .unwrap_or_else(|| i18n::t("notification_no_data"));

    let title = i18n::t_args(
        "notification_title",
        &[
            ("game_name", i18n::Value::from(game_name.as_str())),
            ("resource_name", i18n::Value::from(resource_name.as_str())),
        ],
    );

    app_handle
        .notification()
        .builder()
        .title(&title)
        .body(&body)
        .show()
        .map_err(|e| CommandError {
            code: ErrorCode::NotificationError,
            message: e.to_string(),
        })
}

/// Returns the region derived from a game's UID for display in the settings UI.
/// Client registration applies the same UID-to-region rules.
///
/// # Errors
///
/// Returns [`CommandError`] when the UID does not identify a supported server.
#[tauri::command]
pub fn detect_region(game_id: GameId, uid: &str) -> Result<&'static str, CommandError> {
    let region = match game_id {
        GameId::GenshinImpact => Region::from_genshin_uid(uid),
        GameId::HonkaiStarRail => Region::from_hsr_uid(uid),
        GameId::ZenlessZoneZero => Region::from_zzz_uid(uid),
        GameId::WutheringWaves => Region::from_wuwa_uid(uid),
    }?;

    Ok(region.as_str())
}

/// Returns the list of supported locale codes.
#[tauri::command]
pub fn get_supported_locales() -> Vec<&'static str> {
    i18n::supported_locales()
}

/// Returns the effective locale currently in use by the backend.
#[tauri::command]
pub fn get_effective_locale() -> String {
    i18n::get_current_locale()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use serde_json::json;
    use std::collections::BTreeMap;
    use std::collections::BTreeSet;
    use storekeeper_core::GenshinResourceType;
    use storekeeper_core::HsrResourceType;
    use storekeeper_core::ResourceNotificationConfig;
    use storekeeper_core::WuwaResourceType;
    use storekeeper_core::ZzzResourceType;

    const FRONTEND_SETTINGS_TYPES: &str =
        include_str!("../../frontend/src/modules/settings/settings.types.ts");

    const FRONTEND_GAME_CONSTANTS: &str =
        include_str!("../../frontend/src/modules/games/games.constants.ts");

    fn populated_config() -> Value {
        let game = json!({
            "enabled": true,
            "uid": "800000000",
            "auto_claim_time": "04:00",
            "notifications": {},
        });
        let config: AppConfig = serde_json::from_value(json!({
            "general": { "language": "en" },
            "games": {
                "genshin_impact": game,
                "honkai_star_rail": game,
                "zenless_zone_zero": game,
                "wuthering_waves": game,
            },
        }))
        .expect("fixture should parse");

        serde_json::to_value(&config).expect("config should serialize")
    }

    fn sparse_config() -> Value {
        let game = json!({ "enabled": true, "uid": "800000000" });
        let config: AppConfig = serde_json::from_value(json!({
            "general": {},
            "games": {
                "genshin_impact": game,
                "honkai_star_rail": game,
                "zenless_zone_zero": game,
                "wuthering_waves": game,
            },
        }))
        .expect("fixture should parse");

        serde_json::to_value(&config).expect("config should serialize")
    }

    fn keys_at(json: &Value, pointer: &str) -> BTreeSet<String> {
        json.pointer(pointer)
            .and_then(Value::as_object)
            .expect("the pointer should address an object in the serialized config")
            .keys()
            .cloned()
            .collect()
    }

    fn ts_interface_members(source: &str, name: &str) -> BTreeMap<String, bool> {
        let header = format!("export interface {name} {{");
        assert!(
            source.contains(&header),
            "the frontend should declare `{header}`"
        );

        let mut members = BTreeMap::new();

        for line in source
            .lines()
            .skip_while(|line| line.trim() != header)
            .skip(1)
        {
            let trimmed = line.trim();

            if trimmed == "}" {
                break;
            }
            if trimmed.is_empty() || trimmed.starts_with("/*") || trimmed.starts_with('*') {
                continue;
            }

            assert!(
                trimmed.contains(':'),
                "`{name}` declares a member this parser cannot read: {trimmed}"
            );
            let (lhs, _) = trimmed.split_once(':').expect("the line holds a colon");
            let optional = lhs.ends_with('?');
            let field = lhs.trim_end_matches('?');

            assert!(
                !field.is_empty() && field.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
                "`{name}` declares a member this parser cannot read: {trimmed}"
            );
            members.insert(field.to_string(), optional);
        }

        assert!(!members.is_empty(), "`{name}` should declare fields");
        members
    }

    fn assert_matches_interface(populated: &Value, sparse: &Value, pointer: &str, interface: &str) {
        let rust = keys_at(populated, pointer);
        let members = ts_interface_members(FRONTEND_SETTINGS_TYPES, interface);
        let typescript: BTreeSet<String> = members.keys().cloned().collect();

        assert_eq!(
            rust,
            typescript,
            "`{pointer}` and `{interface}` disagree; \
             Rust-only keys {:?}, TypeScript-only keys {:?}",
            rust.difference(&typescript).collect::<Vec<_>>(),
            typescript.difference(&rust).collect::<Vec<_>>(),
        );

        let omitted: BTreeSet<String> = rust
            .difference(&keys_at(sparse, pointer))
            .cloned()
            .collect();
        let declared_optional: BTreeSet<String> = members
            .iter()
            .filter(|&(_, optional)| *optional)
            .map(|(field, _)| field.clone())
            .collect();

        assert_eq!(
            omitted, declared_optional,
            "`{interface}` marks the wrong fields optional; the backend omits {omitted:?} \
             when unset and serializes every other field, including null"
        );
    }

    fn ts_const_values(source: &str, name: &str) -> BTreeSet<String> {
        let header = format!("export const {name} = {{");
        assert!(
            source.contains(&header),
            "the frontend should declare `{header}`"
        );

        source
            .lines()
            .skip_while(|line| line.trim() != header)
            .skip(1)
            .take_while(|line| !line.trim().starts_with('}'))
            .filter_map(|line| line.split_once(": \""))
            .filter_map(|(_, rhs)| rhs.split_once('"'))
            .map(|(value, _)| value.to_string())
            .collect()
    }

    fn serialized<T: Serialize>(values: &[T]) -> BTreeSet<String> {
        values
            .iter()
            .map(|value| {
                serde_json::to_value(value)
                    .ok()
                    .and_then(|v| v.as_str().map(str::to_string))
                    .expect("a resource type should serialize as a string")
            })
            .collect()
    }

    #[test]
    fn config_structs_match_their_frontend_interfaces() {
        let populated = populated_config();
        let sparse = sparse_config();

        for (pointer, interface) in [
            ("", "AppConfig"),
            ("/general", "GeneralConfig"),
            ("/games", "GamesConfig"),
            ("/games/genshin_impact", "HoyolabGameConfig"),
            ("/games/honkai_star_rail", "HoyolabGameConfig"),
            ("/games/zenless_zone_zero", "HoyolabGameConfig"),
            ("/games/wuthering_waves", "WuwaConfig"),
        ] {
            assert_matches_interface(&populated, &sparse, pointer, interface);
        }
    }

    #[test]
    fn notification_config_matches_frontend_interface() {
        let populated: ResourceNotificationConfig = serde_json::from_value(json!({
            "notify_minutes_before_full": 60,
            "notify_at_value": 180,
        }))
        .expect("fixture should parse");
        let sparse: ResourceNotificationConfig =
            serde_json::from_value(json!({})).expect("fixture should parse");

        assert_matches_interface(
            &serde_json::to_value(&populated).expect("should serialize"),
            &serde_json::to_value(&sparse).expect("should serialize"),
            "",
            "ResourceNotificationConfig",
        );
    }

    #[test]
    fn secrets_structs_match_their_frontend_interfaces() {
        let secrets = serde_json::to_value(SecretsConfig::default()).expect("should serialize");

        for (pointer, interface) in [
            ("", "SecretsConfig"),
            ("/hoyolab", "HoyolabSecrets"),
            ("/kuro", "KuroSecrets"),
        ] {
            assert_matches_interface(&secrets, &secrets, pointer, interface);
        }
    }

    #[test]
    fn save_result_matches_frontend_interface() {
        let result = serde_json::to_value(SaveResult {
            effective_locale: "en".to_string(),
        })
        .expect("should serialize");

        assert_matches_interface(&result, &result, "", "SaveResult");
    }

    #[test]
    fn frontend_resource_keys_match_the_backend_defaults() {
        for (constant, rust) in [
            ("GenshinResource", serialized(GenshinResourceType::all())),
            ("HsrResource", serialized(HsrResourceType::all())),
            ("ZzzResource", serialized(ZzzResourceType::all())),
            ("WuwaResource", serialized(WuwaResourceType::all())),
        ] {
            assert_eq!(
                ts_const_values(FRONTEND_GAME_CONSTANTS, constant),
                rust,
                "`{constant}` and its backend resource type disagree"
            );
        }
    }

    #[test]
    fn detect_region_reports_each_game_its_own_server() {
        assert_eq!(
            detect_region(GameId::GenshinImpact, "900000001").expect("a traditional-Chinese uid"),
            "china_hmt"
        );
        assert_eq!(
            detect_region(GameId::ZenlessZoneZero, "1712345678")
                .expect("a traditional-Chinese uid"),
            "china_hmt"
        );
        assert_eq!(
            detect_region(GameId::WutheringWaves, "902763418").expect("a southeast-asian uid"),
            "sea"
        );
        assert_eq!(
            detect_region(GameId::HonkaiStarRail, "600000001").expect("an american uid"),
            "america"
        );
    }

    #[test]
    fn detect_region_rejects_a_uid_naming_no_server() {
        let err = detect_region(GameId::GenshinImpact, "400000001")
            .expect_err("prefix 4 names no Genshin server");

        assert!(
            matches!(err.code, ErrorCode::ConfigInvalid),
            "an undetectable UID is a configuration problem, got {:?}",
            err.code
        );
    }
}
