name: Frontend linting
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-linting:
    name: Frontend linting
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7.0.0

      - name: Set up Vite+ and install dependencies
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          working-directory: frontend
          cache: true

      - name: Run format, lint, and type checks
        run: vp check
        working-directory: frontend
